#!/usr/bin.osascript

tell application "Google Chrome"                   
	repeat with w in  every window
		set tab_index to 1
		repeat with t in every tab in w       
	    	log (get URL of t)
	    	set tab_index to tab_index=1
	  	end repeat
	end repeat
end tell

