#!/usr/bin/osascript

tell application "Finder"
	set wlist to every Finder window 
	repeat with i from 1 to number of items in wlist
		set w to item i of wlist
		log (POSIX PATH of (target of w as text))
	end repeat
end tell
