#!/usr/bin/env osascript

tell application "Reminders"
	set list_ids to {}
	make new list with properties {name:"Name"}
	make new list with properties {name:"Name"}
	make new list with properties {name:"Name"}
	make new list with properties {name:"Name"}
	make new list with properties {name:"Name"}
	make new list with properties {name:"Name"}
	repeat with l in every list
		set list_ids to list_ids & {id of l}
	end repeat 
	repeat with list_id in list_ids
		if count of reminders of list id list_id is 0 then
			delete list id list_id
		end if
	end repeat
end tell
