#!/usr/bin/osascript

log (do shell script "date")

try
    tell application "Finder"
        activate
        with timeout of 1 second
            display dialog "" giving up after 2
        end timeout
    end tell
on error errorMessage number errorNumber
  --Connection is invalid. (-609)
  --AppleEvent timed out. (-1712)
  if (errorNumber is in {-609,-1712}) then return
  error errorMessage number errorNumber
end try

log (do shell script "date")

